Rework signers
alicenet/alicenetjs pull request #65
Opened 2022-09-02 20:52 UTC by rfrabasile

2022-09-14 19:02 UTC, everton0991 commented on src/Signers/MultiSig.js
> +            if (!this.publicKeys || +this.publicKeys.length === 0) {
I would suggest using Number() or parseInt() here for consistency and easy to read instead of `+`.

2022-09-14 19:02 UTC, everton0991 commented on src/Signers/MultiSig.js
> +            if (!this.publicKeys || +this.publicKeys.length === 0) {
Same as above

2022-09-14 19:06 UTC, everton0991 requested changes
Small suggestion.

2022-10-04 16:09 UTC, ACatThatPrograms approved these changes

2022-10-04 16:11 UTC, merged